# Copyright 2019 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0

#apiVersion: examples.config.kubernetes.io/v1beta1
#kind: Kubeval
#metadata:
#  configFn:
#    container:
#        image: quay.io/airshipit/replacement-function:v0.1.0
#spec:
#  strict: true
#  ignoreMissingSchemas: true
#
#  # TODO: Remove these once function container network/volumes features are
#  # stabilized.
#  # Relevant issues:
#  #   - https://github.com/kubernetes-sigs/kustomize/issues/1901
#  #   - https://github.com/kubernetes-sigs/kustomize/issues/1902
#  kubernetesVersion: "1.16.0"
#  schemaLocation: "file:///schemas"
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: label-catalogue
  annotation:
    config.kubernetes.io/local-config: "true"
#    config.kubernetes.io/function: |
#      container:
#        image: quay.io/airshipit/replacement-function:v0.1.0
spec:
  environmentLabel: prod
---
apiVersion: v1
kind: Service
metadata:
  name: svc
#  annotation:
#    config.kubernetes.io/function: |
#      container:
#        image: quay.io/airshipit/replacement-function:v0.1.0
  labels:
    environment: dev
spec:
  clusterIP: None
  poo: poo
---
apiVersion: someteam.example.com/v1
kind: ReplacementTransformer
metadata:
  name: notImportantHere
  annotations:
    config.kubernetes.io/local-config: "true"
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/example-validator-kubeval:v0.1.0
replacements:
- source:
    objref:
      apiversion: airshipit.org/v1alpha1
      kind: VariableCatalogue
      name: label-catalogue
    fieldref: spec.environmentLabel
  target:
    objref:
      apiversion: airshipit.org/v1alpha1
      kind: Service
      name: svc
    fieldrefs:
    - metadata.labels.environment

---
apiVersion: examples.config.kubernetes.io/v1beta1
kind: Kubeval
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: gcr.io/kustomize-functions/example-validator-kubeval:v0.1.0
spec:
  strict: true
  ignoreMissingSchemas: true

  # TODO: Remove these once function container network/volumes features are
  # stabilized.
  # Relevant issues:
  #   - https://github.com/kubernetes-sigs/kustomize/issues/1901
  #   - https://github.com/kubernetes-sigs/kustomize/issues/1902
  kubernetesVersion: "1.16.0"
  schemaLocation: "file:///schemas"
